schema_version = "1.0.0"

id = "sollumz_rdr_dev"
version = "2.6.1-rdr_dev+$Format:%h$"
name = "Sollumz RDR (Development)"
tagline = "Experimental fork with Red Dead Redemption 2 support"
maintainer = "ultrahacx, alexguirre <alexguirre.aa@gmail.com>"
type = "add-on"

website = "https://docs.sollumz.org"

tags = ["Import-Export"]

blender_version_min = "4.2.0"

license = ["SPDX:MIT"]
copyright = ["2020-2024 Skylumz, Colton and alexguirre"]

[permissions]
files = "Import/export CodeWalker XML files. Save/load presets."
clipboard = "Copy/paste location and rotation of objects."

